### ISSUE TITLE
Cannot convert undefined to a BigInt #300

### ISSUE THREAD

**Issue by koolwithk** [spacebudz/lucid#144]
#### What Git revision are you using? 
deno 1.29.4 (release, x86_64-unknown-linux-gnu)
v8 10.9.194.5
typescript 4.9.4
node v18.7.0
aiken v0.0.28
git 2.38.1

#### What operating system are you using, and which version?

- [ x] Linux / Other 

#### Describe what the problem is? 
cannot submit the `hello_world-lock.ts` transaction as described here https://aiken-lang.org/getting-started/hello-world#setup

I'm getting this error.

```bash
[home@fedora hello_world]$ deno run --allow-net --allow-read 2.lock.ts
error: Uncaught (in promise) TypeError: Cannot convert undefined to a BigInt
      keyDeposit: BigInt(result.key_deposit),
                  ^
    at BigInt (<anonymous>)
    at Blockfrost.getProtocolParameters (https://deno.land/x/lucid@0.8.3/src/provider/blockfrost.ts:38:19)
    at async Function.new (https://deno.land/x/lucid@0.8.3/src/lucid/lucid.ts:52:34)
    at async file:///home/alok/cardano-lucid/hello_world/2.lock.ts:15:15
```

### `2.lock.ts`
```javascript
import {
  Blockfrost,
  C,
  Constr,
  Data,
  Lucid,
  SpendingValidator,
  TxHash,
  fromHex,
  toHex,
  utf8ToHex,
} from "https://deno.land/x/lucid@0.8.3/mod.ts";
import * as cbor from "https://deno.land/x/cbor@v1.4.1/index.js";
 
const lucid = await Lucid.new(
  new Blockfrost(
    "https://cardano-preview.blockfrost.io/api/v0",
    "TOKEN"
  ),
  "Preview",
);
 
lucid.selectWalletFromPrivateKey(await Deno.readTextFile("./key.sk"));
 
const validator = await readValidator("./assets/hello_world/spend/script.cbor");
 
  async function readValidator(filepath: String): Promise<SpendingValidator> {
    return {
    type: "PlutusV2",
    script: toHex(cbor.encode(fromHex(await Deno.readTextFile(filepath)))),
    };
  }
 
  const publicKeyHash = lucid.utils
  .getAddressDetails(await lucid.wallet.address())
  .paymentCredential
  .hash;

  const datum = Data.to(new Constr(0, [publicKeyHash]));

  const txLock = await lock(10000000, { into: validator, owner: datum });

  await lucid.awaitTx(txLock);

  console.log(`10 ADA locked into the contract
    Tx ID: ${txLock}
    Datum: ${datum}
  `);

async function lock(lovelace, { into, owner }): Promise<TxHash>{
  const contractAddress = lucid.utils.validatorToAddress(into);
 
  const tx = await lucid
    .newTx()
    .payToContract(contractAddress, { inline: owner }, { lovelace })
    .complete();
 
  const signedTx = await tx
    .sign()
    .complete();
 
  return signedTx.submit();
}
```

#### What should be the expected behavior?
the transaction should be completed.

**Comment by alessandrokonrad** [comment]
You need to replace `TOKEN` with a Blockfrost Api key.

**Comment by koolwithk** [comment]
It's Blockfrost API key only. I just added `TOKEN` above so I don't reveal my token.

**Comment by koolwithk** [comment]
Okay, So I got to know I was using an `old expired Blockfrost API ` Token. After updating the new API token It worked. 
I just started learning javascript I will see if I can modify the code for a better error message.
Thank you! @alessandrokonrad
