### ISSUE TITLE
throws error when trying to send multiple transactions

### ISSUE THREAD

**Issue by MohiuddinM** [spacebudz/lucid#160]
I get the following error when I try to send multiple transactions:
```
Error: "transaction submit error ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (UtxoFailure (FromAlonzoUtxoFail (ValueNotConservedUTxO (Value 1417616097 (fromList [])) (Value 3997301460 (fromList []))))),UtxowFailure (UtxoFailure (FromAlonzoUtxoFail (BadInputsUTxO (fromList [TxIn (TxId {_unTxId = SafeHash \"5259ff6a04ca3226173g7fcdbfcd7a2e34b82f7857d72096b3cd9e25d95021f7\"}) (TxIx 1)]))))])"
    at Blockfrost.submitTx (file:///node_modules/lucid-cardano/esm/src/provider/blockfrost.js:177:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.submitTx (file:///node_modules/lucid-cardano/esm/src/lucid/lucid.js:371:24)
    at async TxSigned.submit (file:///node_modules/lucid-cardano/esm/src/lucid/tx_signed.js:21:16)
```

**Comment by MohiuddinM** [comment]
Also, can someone guide me on how to use Kupmios, because blockfrost is giving too many errors?

**Comment by alessandrokonrad** [comment]
Hey, you usually have to wait until one transaction is confirmed on the blockchain before submitting another one. You can only send multiple transactions in a row when one transactions doesn't depend on another, or in other words all txs use unique utxos and don't reuse the ones from another tx.

**Comment by MohiuddinM** [comment]
Is there a way to know or wait until the previous transaction is confirmed?

**Comment by alessandrokonrad** [comment]
Yes, after submitting a tx you get back the tx hash. You could the following:
```js
const tx = await lucid.newTx()
//....

const txHash = await tx.submit();

await lucid.awaitTx(txHash);

//... submit another tx
```

**Comment by MohiuddinM** [comment]
Thanks a lot, I will try that.
