### ISSUE TITLE
cannot find npm 

### ISSUE THREAD

**Issue by besiwims** [spacebudz/lucid#177]
When I run deno task build i get this error

deno task build
Task build deno run --allow-env --allow-write --allow-read --allow-net --allow-run build.ts
[dnt] Transforming...
[dnt] Running npm install...
error: Uncaught (in promise) Error: Could not find command 'npm'. Ensure it is available on the path.
      throw new Error(
            ^
    at runCommand (https://deno.land/x/dnt@0.30.0/lib/utils.ts:67:13)
    at async Module.build (https://deno.land/x/dnt@0.30.0/mod.ts:198:5)
    at async file:///home/wims/lucid/build.ts:9:1
Caused by: NotFound: No such file or directory (os error 2)
    at opRun (deno:runtime/js/40_process.js:33:16)
    at Object.run (deno:runtime/js/40_process.js:116:17)
    at runCommand (https://deno.land/x/dnt@0.30.0/lib/utils.ts:45:26)
    at async Module.build (https://deno.land/x/dnt@0.30.0/mod.ts:198:5)
    at async file:///home/wims/lucid/build.ts:9:1

How do I fix this, please help

**Comment by GGAlanSmithee** [comment]
do you have `npm` installed? What does running `npm --version` from a bash show?

**Comment by besiwims** [comment]
npm --version
9.4.0

**Comment by GGAlanSmithee** [comment]
hmm.. interesting. What operating system are you on? Depending on that, you need to make sure that `npm` is accessable from the path (checking advanced system settings -> Environment variables on windows, or `echo $PATH` on Linux) but honestly I would surprise me if this is the problem, because any standars installation of NodeJS should take care of this for you.

**Comment by besiwims** [comment]
Linux 
echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Comment by besiwims** [comment]
What other alternative do I have?

wims@wimspc:~/lucid$ deno task build
Task build deno run --allow-env --allow-write --allow-read --allow-net --allow-run build.ts
[dnt] Transforming...
[dnt] Running npm install...
error: Uncaught (in promise) Error: Could not find command 'npm'. Ensure it is available on the path.
      throw new Error(
            ^
    at runCommand (https://deno.land/x/dnt@0.30.0/lib/utils.ts:67:13)
    at async Module.build (https://deno.land/x/dnt@0.30.0/mod.ts:198:5)
    at async file:///home/wims/lucid/build.ts:9:1
Caused by: NotFound: No such file or directory (os error 2)
    at opRun (deno:runtime/js/40_process.js:33:16)
    at Object.run (deno:runtime/js/40_process.js:116:17)
    at runCommand (https://deno.land/x/dnt@0.30.0/lib/utils.ts:45:26)
    at async Module.build (https://deno.land/x/dnt@0.30.0/mod.ts:198:5)
    at async file:///home/wims/lucid/build.ts:9:1
wims@wimspc:~/lucid$ npm --version
9.4.0

**Comment by besiwims** [comment]
I managed to get mesh with lucid run

**Comment by GGAlanSmithee** [comment]
amazing!
