### ISSUE TITLE
ReferenceError: module is not defined

### ISSUE THREAD

**Issue by sk-shishi** [spacebudz/lucid#179]
I'm having this issue with lucid-cardano `0.9.8` in Node.js env (with ESM)

``` 
ReferenceError: module is not defined

      at __wbg_static_accessor_NODE_MODULE_06b864c18e8ae506 (node_modules/lucid-cardano/esm/src/core/libs/cardano_multiplatform_lib/cardano_multiplatform_lib.generated.js:21973:25)
      at null.<anonymous> (wasm:/wasm/009949de:1:2246391)
      at null.<anonymous> (wasm:/wasm/009949de:1:2246688)
      at null.<anonymous> (wasm:/wasm/009949de:1:2203164)
      at null.<anonymous> (wasm:/wasm/009949de:1:2248789)
      at null.<anonymous> (wasm:/wasm/009949de:1:2175037)
      at null.<anonymous> (wasm:/wasm/009949de:1:1898472)
      at TransactionBuilder.add_inputs_from (node_modules/lucid-cardano/esm/src/core/libs/cardano_multiplatform_lib/cardano_multiplatform_lib.generated.js:17398:18)
      at Tx.complete (node_modules/lucid-cardano/esm/src/lucid/tx.js:331:28)
```

**Comment by alessandrokonrad** [comment]
I'm trying to figure this out. Seems like pure ESM and WASM doesn't work with node.js. I probably need to generate a seprate file for node.js to interact with WASM properly, which is quite unfortunate.

**Comment by alessandrokonrad** [comment]
Alright Lucid `0.9.9` should fix node.js issues once and for all.
